AWSTemplateFormatVersion: 2010-09-09
Description: Creating ECS service
Parameters:
  DevECRName:
    Type: String
    Description: Name of the Dev ECR Repo
    Default: dev-scala-image-repo
  StagingECRName:
    Type: String
    Description: Name of the Staging ECR Repo
    Default: staging-scala-image-repo
  DevIAMUser:
    Type: String
    Description: User
    Default: arn:aws:iam::205376115077:user/cloud_user
  ProdIAMUser:
    Type: String
    Description: User
    Default: arn:aws:iam::667333752349:user/pavan
  AccountID:
    Type: String
    Description: AccountID
    Default: 205376115077
    
Resources:       
  ECRA: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: 
         Ref: DevECRName
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                Ref: DevIAMUser, 
                Ref: ProdIAMUser
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
           
  ECRB: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName:
         Ref: StagingECRName
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                Ref: DevIAMUser            
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
