AWSTemplateFormatVersion: 2010-09-09
Description: Creating ECS service
Parameters:
  DevECRName:
    Type: String
    Description: Name of the Dev ECR Repo
    Default: dev-scala-image-repo
  StagingECRName:
    Type: String
    Description: Name of the Staging ECR Repo
    Default: staging-scala-image-repo
  User:
    Type: String
    Description: User
    Default: arn:aws:iam::740121593245:user/cloud_user
  AccountID:
    Type: String
    Description: AccountID
    Default: 206406752358
    
Resources:       
  ECRA: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: 
         Ref: DevECRName
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                Ref: User              
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
           
  ECRB: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName:
         Ref: StagingECRName
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                Ref: User            
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
